# Generated by Django 5.2 on 2025-06-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
