# Generated by Django 5.2 on 2025-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_userdetails_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='adults',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='kids',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
