# Generated by Django 5.2 on 2025-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_userdetails_address_alter_userdetails_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
