# Generated by Django 5.2 on 2025-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_userdetails_city_alter_userdetails_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=30),
        ),
    ]
